// Starting points for posting a calendar event. Picking one fills in the
// form with a name, a plain-language outline to finish, how long it usually
// runs, and sensible sign-up and privacy settings. Everything stays
// editable. Keep the outlines short and in plain words: the people reading
// them may be tired, stressed, or reading in a second language.
//
// Fields:
//   key, icon, name, blurb   what shows on the "What kind of event?" card
//   title                    starting event name
//   durationMins             fills in the end time once a start is picked
//   visibility               'public' | 'members' | 'invite'
//                            ('members' falls back to 'invite' when VWB
//                            itself hosts, since members-only needs a group)
//   signupEnabled, signupLimit
//   hideAddress              true for events at someone's home
//   radius                   miles
//   description              the outline. Lines ending in ":" are prompts.

const ACCESS = 'Access: (parking, steps or ramp, restrooms, seating, quiet space, ASL, anything else people should know)'
const CONTACT = 'Questions? Reach out to:'

export const EVENT_TEMPLATES = [
  {
    key: 'food',
    icon: '\u{1F96B}',
    name: 'Food drive or food share',
    blurb: 'Collect or hand out food',
    title: 'Community food share',
    durationMins: 180,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: 10,
    hideAddress: false,
    radius: 25,
    description: [
      "What we're doing:",
      '',
      'Who it\'s for: Anyone who needs food. No ID or paperwork needed.',
      '',
      'What to bring (if donating): Canned and boxed food, baby food, pet food. No glass, please.',
      '',
      'Volunteers: Sign up to help sort, pack, or hand out food.',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'supplies',
    icon: '\u{1F4E6}',
    name: 'Supply drive',
    blurb: 'Hygiene kits, school or winter supplies',
    title: 'Supply drive',
    durationMins: 180,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: '',
    hideAddress: false,
    radius: 25,
    description: [
      "What we're collecting:",
      '',
      "What we need most right now:",
      '',
      "Please don't bring:",
      '',
      'Drop-off times:',
      '',
      'Volunteers: Sign up to help sort and pack.',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'cleanup',
    icon: '\u{1F30A}',
    name: 'Storm, flood, or mold cleanup',
    blurb: 'A workday at a home or street',
    title: 'Cleanup workday',
    durationMins: 240,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: 12,
    hideAddress: true,
    radius: 25,
    description: [
      "What we're doing: (for example, clearing limbs, pulling wet drywall, carrying out damaged things)",
      '',
      'What to wear and bring: Work gloves, closed-toe boots, long pants, water. For mold: an N95 mask and eye protection. We\'ll have some to share.',
      '',
      'Staying safe: Take breaks. If you have asthma or a weak immune system, help outside the house instead, like sorting, driving, or bringing food.',
      '',
      'Where: The address goes only to people who sign up, to protect the family.',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'litter',
    icon: '\u{1F6AE}',
    name: 'Trash pickup',
    blurb: 'Clean up a road, park, or creek',
    title: 'Community trash pickup',
    durationMins: 150,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: 20,
    hideAddress: false,
    radius: 25,
    description: [
      'Where we meet:',
      '',
      "What we're cleaning up: (road, park, creek bank, neighborhood)",
      '',
      "We'll have: Trash bags, gloves, and grabbers to share.",
      '',
      'Wear and bring: Closed-toe shoes, long pants, a hat, water, and sunscreen. Bring your own gloves if you have them.',
      '',
      "Staying safe: Don't pick up needles, broken glass, or anything that looks dangerous. Mark the spot and tell an organizer. Stay well off the road and wear something bright. Kids are welcome with an adult.",
      '',
      'Where the trash goes:',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'tenant',
    icon: '\u{1F3E0}',
    name: 'Tenant rights help',
    blurb: 'Know-your-rights or paperwork help',
    title: 'Tenant rights help session',
    durationMins: 120,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: '',
    hideAddress: false,
    radius: 25,
    description: [
      'What this is: A free, friendly time to ask questions about renting, repairs, notices, and evictions.',
      '',
      'Bring if you have them: Your lease, any notices or letters from your landlord, photos of repairs needed. Copies or phone pictures are fine.',
      '',
      'Good to know: This is information and support, not legal advice. We can help you find a lawyer if you need one.',
      '',
      'Sign up so we know how many to expect. You can still come if you don\'t.',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'skillshare',
    icon: '\u{1F6E0}\u{FE0F}',
    name: 'Skill share or workshop',
    blurb: 'Teach or learn something together',
    title: 'Skill share',
    durationMins: 120,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: 12,
    hideAddress: false,
    radius: 25,
    description: [
      "What we'll learn:",
      '',
      'Who can come: Everyone. No experience needed.',
      '',
      'What to bring:',
      '',
      'Spots are limited so everyone gets hands-on time.',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'meal',
    icon: '\u{1F372}',
    name: 'Community meal or potluck',
    blurb: 'Share a meal together',
    title: 'Community meal',
    durationMins: 120,
    visibility: 'public',
    signupEnabled: false,
    signupLimit: '',
    hideAddress: false,
    radius: 25,
    description: [
      "What's on the table:",
      '',
      'Everyone is welcome, whether or not you bring a dish.',
      '',
      'If you bring food: Please put a card by it listing what\'s in it (nuts, dairy, gluten, meat).',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'orientation',
    icon: '\u{1F64B}',
    name: 'Volunteer orientation',
    blurb: 'Welcome new helpers',
    title: 'New volunteer welcome',
    durationMins: 90,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: '',
    hideAddress: false,
    radius: 25,
    description: [
      "What we'll cover: How we work, how to stay safe, and ways to help that fit your time and skills.",
      '',
      'Who should come: Anyone thinking about helping out. No experience needed.',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'resourcefair',
    icon: '\u{1F91D}',
    name: 'Resource fair',
    blurb: 'Local groups share what they offer',
    title: 'Community resource fair',
    durationMins: 180,
    visibility: 'public',
    signupEnabled: true,
    signupLimit: '',
    hideAddress: false,
    radius: 50,
    description: [
      "Who'll be there:",
      '',
      'What you can get help with: (food, housing, health, jobs, benefits, childcare)',
      '',
      'Groups: Sign up to reserve a table.',
      '',
      ACCESS,
      '',
      CONTACT,
    ].join('\n'),
  },
  {
    key: 'meeting',
    icon: '\u{1F5D3}\u{FE0F}',
    name: 'Group meeting',
    blurb: 'Plan together, members only',
    title: 'Group meeting',
    durationMins: 60,
    visibility: 'members',
    signupEnabled: false,
    signupLimit: '',
    hideAddress: true,
    radius: 25,
    description: [
      "What we'll talk about:",
      '',
      'How to join: (in person, phone, or video link)',
      '',
      ACCESS,
    ].join('\n'),
  },
]

// "14:30" + 90 minutes -> "16:00". Wraps past midnight.
export function addMinutes(time, mins) {
  if (!time || !mins) return ''
  const [h, m] = time.split(':').map(Number)
  const total = (h * 60 + m + mins) % (24 * 60)
  return String(Math.floor(total / 60)).padStart(2, '0') + ':' + String(total % 60).padStart(2, '0')
}
